platform :ios, '9.0'

target 'SceneMachine-Example' do

  use_frameworks!

  pod 'SceneMachine', :path => '../'

  target 'SceneMachine-ExampleTests' do
    inherit! :search_paths
  end

  target 'SceneMachine-ExampleUITests' do
  end

end
